### ISSUE TITLE
筛刀过程中，使用插件结算某BOSS数据并不会更新BOSS血量

### ISSUE THREAD

**Issue by sdyxxjj123** [pcrbot/filter_knife#2]
试用了一下，发现在令某一位参与者结算后，插件内的BOSS血量并不会更新。

**Comment by H-K-Y** [comment]
你Git pull一下试试，现在报筛刀和查看筛刀信息之前都会更新bosss生命值了

**Comment by H-K-Y** [comment]
boss的血量要实际报刀之后才会更新，筛刀的提醒结算是不会更新的
